comb_brushes = {
    184: ['Red undertail feathers', 'Red undertail feathers_White wing stripe',
          'Red undertail feathers_White wing stripe_gray belly', 'Red undertail feathers_gray belly',
          'White wing stripe', 'White wing stripe_gray belly', 'gray belly'],
    185: ['white undertail region', 'white undertail region_yellow belly', 'yellow belly'],
    128: ['reddish-brown stripes on head', 'reddish-brown stripes on head_stripes meet in middle of chest',
          'reddish-brown stripes on head_stripes meet in middle of chest_whitish mustache stripe near beak',
          'reddish-brown stripes on head_whitish mustache stripe near beak', 'stripes meet in middle of chest',
          'stripes meet in middle of chest_whitish mustache stripe near beak', 'whitish mustache stripe near beak'],
    131: ['black striped head', 'black striped head_orange-pink bill',
          'black striped head_orange-pink bill_peaked head shape', 'black striped head_peaked head shape',
          'brown striped head', 'brown striped head_orange-pink bill',
          'brown striped head_orange-pink bill_peaked head shape', 'brown striped head_peaked head shape',
          'orange-pink bill', 'orange-pink bill_peaked head shape', 'peaked head shape'],
    132: ['black head stripes', 'black head stripes_white throat patch',
          'black head stripes_white throat patch_yellow eye spot', 'black head stripes_yellow eye spot',
          'brown head stripes (juvenile)', 'brown head stripes (juvenile)_white throat patch',
          'brown head stripes (juvenile)_white throat patch_yellow eye spot',
          'brown head stripes (juvenile)_yellow eye spot', 'white throat patch', 'white throat patch_yellow eye spot',
          'yellow eye spot'],
}

brushes = {
    184: ['Red undertail feathers', 'White wing stripe', 'gray belly'],
    185: ['white undertail region', 'yellow belly'],
    128: ['reddish-brown stripes on head', 'stripes meet in middle of chest', 'whitish mustache stripe near beak'],
    131: ['black striped head', 'brown striped head', 'orange-pink bill', 'peaked head shape'],
    132: ['black head stripes', 'brown head stripes (juvenile)', 'white throat patch', 'yellow eye spot'],
    1: ['pale, hooked bill', 'dark shading on face', 'white head', 'white rump'],
    0: ['white ring around bill', 'dark body'],
    4: ['pale eye', 'orange bill', 'single white streak', 'white underneath'],
    7: ['two white face streaks', 'horn on beak', 'gray underneath'],
    6: ['pale eye', 'bright orange bill', 'single white streak', 'forward crest'],
    192: ['Long curved beak', 'dark barring on long tail', 'white eyebrow'],
    193: ['white and black striping undertail', 'bright white eyebrow', 'cinammon (brown/yellow) sides'],
    194: ['Reddish-brown upper part', 'white throat', 'white eyebrow'],
    195: ['dark barring (stripes) on wings', 'dark barring (stripes) on tail', 'pale throat', 'thin bill'],
    196: ['pale eyebrow', 'Rusty-brown upper part with black and white streaks'],
}
remap_brushes_dict = {
    'Red undertail feathers': 'red undertail feathers',
    'White wing stripe': 'white wing stripe',
    'reddish-brown stripes on head': 'reddish-brown striped head',
    'brown striped head': 'brown striped head (juvenile)',
    'black head stripes': 'black striped head',
    'brown head stripes (juvenile)': 'brown striped head (juvenile)',
}
